library feather_icons;

import "package:flutter/widgets.dart";
import "src/icon_data.dart";

// THIS FILE IS AUTOMATICALLY GENERATED!

const Map<String, IconData> FeatherIconsMap = {
  'icon-activity': const FeatherIconData(0xe900),
  'icon-airplay': const FeatherIconData(0xe901),
  'icon-alert-circle': const FeatherIconData(0xe902),
  'icon-alert-octagon': const FeatherIconData(0xe903),
  'icon-alert-triangle': const FeatherIconData(0xe904),
  'icon-align-center': const FeatherIconData(0xe905),
  'icon-align-justify': const FeatherIconData(0xe906),
  'icon-align-left': const FeatherIconData(0xe907),
  'icon-align-right': const FeatherIconData(0xe908),
  'icon-anchor': const FeatherIconData(0xe909),
  'icon-aperture': const FeatherIconData(0xe90a),
  'icon-archive': const FeatherIconData(0xe90b),
  'icon-arrow-down': const FeatherIconData(0xe90c),
  'icon-arrow-down-circle': const FeatherIconData(0xe90d),
  'icon-arrow-down-left': const FeatherIconData(0xe90e),
  'icon-arrow-down-right': const FeatherIconData(0xe90f),
  'icon-arrow-left': const FeatherIconData(0xe910),
  'icon-arrow-left-circle': const FeatherIconData(0xe911),
  'icon-arrow-right': const FeatherIconData(0xe912),
  'icon-arrow-right-circle': const FeatherIconData(0xe913),
  'icon-arrow-up': const FeatherIconData(0xe914),
  'icon-arrow-up-circle': const FeatherIconData(0xe915),
  'icon-arrow-up-left': const FeatherIconData(0xe916),
  'icon-arrow-up-right': const FeatherIconData(0xe917),
  'icon-at-sign': const FeatherIconData(0xe918),
  'icon-award': const FeatherIconData(0xe919),
  'icon-bar-chart': const FeatherIconData(0xe91a),
  'icon-bar-chart-2': const FeatherIconData(0xe91b),
  'icon-battery': const FeatherIconData(0xe91c),
  'icon-battery-charging': const FeatherIconData(0xe91d),
  'icon-bell': const FeatherIconData(0xe91e),
  'icon-bell-off': const FeatherIconData(0xe91f),
  'icon-bluetooth': const FeatherIconData(0xe920),
  'icon-bold': const FeatherIconData(0xe921),
  'icon-book': const FeatherIconData(0xe922),
  'icon-book-open': const FeatherIconData(0xe923),
  'icon-bookmark': const FeatherIconData(0xe924),
  'icon-box': const FeatherIconData(0xe925),
  'icon-briefcase': const FeatherIconData(0xe926),
  'icon-calendar': const FeatherIconData(0xe927),
  'icon-camera': const FeatherIconData(0xe928),
  'icon-camera-off': const FeatherIconData(0xe929),
  'icon-cast': const FeatherIconData(0xe92a),
  'icon-check': const FeatherIconData(0xe92b),
  'icon-check-circle': const FeatherIconData(0xe92c),
  'icon-check-square': const FeatherIconData(0xe92d),
  'icon-chevron-down': const FeatherIconData(0xe92e),
  'icon-chevron-left': const FeatherIconData(0xe92f),
  'icon-chevron-right': const FeatherIconData(0xe930),
  'icon-chevron-up': const FeatherIconData(0xe931),
  'icon-chevrons-down': const FeatherIconData(0xe932),
  'icon-chevrons-left': const FeatherIconData(0xe933),
  'icon-chevrons-right': const FeatherIconData(0xe934),
  'icon-chevrons-up': const FeatherIconData(0xe935),
  'icon-chrome': const FeatherIconData(0xe936),
  'icon-circle': const FeatherIconData(0xe937),
  'icon-clipboard': const FeatherIconData(0xe938),
  'icon-clock': const FeatherIconData(0xe939),
  'icon-cloud': const FeatherIconData(0xe93a),
  'icon-cloud-drizzle': const FeatherIconData(0xe93b),
  'icon-cloud-lightning': const FeatherIconData(0xe93c),
  'icon-cloud-off': const FeatherIconData(0xe93d),
  'icon-cloud-rain': const FeatherIconData(0xe93e),
  'icon-cloud-snow': const FeatherIconData(0xe93f),
  'icon-code': const FeatherIconData(0xe940),
  'icon-codepen': const FeatherIconData(0xe941),
  'icon-codesandbox': const FeatherIconData(0xe942),
  'icon-coffee': const FeatherIconData(0xe943),
  'icon-columns': const FeatherIconData(0xe944),
  'icon-command': const FeatherIconData(0xe945),
  'icon-compass': const FeatherIconData(0xe946),
  'icon-copy': const FeatherIconData(0xe947),
  'icon-corner-down-left': const FeatherIconData(0xe948),
  'icon-corner-down-right': const FeatherIconData(0xe949),
  'icon-corner-left-down': const FeatherIconData(0xe94a),
  'icon-corner-left-up': const FeatherIconData(0xe94b),
  'icon-corner-right-down': const FeatherIconData(0xe94c),
  'icon-corner-right-up': const FeatherIconData(0xe94d),
  'icon-corner-up-left': const FeatherIconData(0xe94e),
  'icon-corner-up-right': const FeatherIconData(0xe94f),
  'icon-cpu': const FeatherIconData(0xe950),
  'icon-credit-card': const FeatherIconData(0xe951),
  'icon-crop': const FeatherIconData(0xe952),
  'icon-crosshair': const FeatherIconData(0xe953),
  'icon-database': const FeatherIconData(0xe954),
  'icon-delete': const FeatherIconData(0xe955),
  'icon-disc': const FeatherIconData(0xe956),
  'icon-dollar-sign': const FeatherIconData(0xe957),
  'icon-download': const FeatherIconData(0xe958),
  'icon-download-cloud': const FeatherIconData(0xe959),
  'icon-droplet': const FeatherIconData(0xe95a),
  'icon-edit': const FeatherIconData(0xe95b),
  'icon-edit-2': const FeatherIconData(0xe95c),
  'icon-edit-3': const FeatherIconData(0xe95d),
  'icon-external-link': const FeatherIconData(0xe95e),
  'icon-eye': const FeatherIconData(0xe95f),
  'icon-eye-off': const FeatherIconData(0xe960),
  'icon-facebook': const FeatherIconData(0xe961),
  'icon-fast-forward': const FeatherIconData(0xe962),
  'icon-feather': const FeatherIconData(0xe963),
  'icon-figma': const FeatherIconData(0xe964),
  'icon-file': const FeatherIconData(0xe965),
  'icon-file-minus': const FeatherIconData(0xe966),
  'icon-file-plus': const FeatherIconData(0xe967),
  'icon-file-text': const FeatherIconData(0xe968),
  'icon-film': const FeatherIconData(0xe969),
  'icon-filter': const FeatherIconData(0xe96a),
  'icon-flag': const FeatherIconData(0xe96b),
  'icon-folder': const FeatherIconData(0xe96c),
  'icon-folder-minus': const FeatherIconData(0xe96d),
  'icon-folder-plus': const FeatherIconData(0xe96e),
  'icon-framer': const FeatherIconData(0xe96f),
  'icon-frown': const FeatherIconData(0xe970),
  'icon-gift': const FeatherIconData(0xe971),
  'icon-git-branch': const FeatherIconData(0xe972),
  'icon-git-commit': const FeatherIconData(0xe973),
  'icon-git-merge': const FeatherIconData(0xe974),
  'icon-git-pull-request': const FeatherIconData(0xe975),
  'icon-github': const FeatherIconData(0xe976),
  'icon-gitlab': const FeatherIconData(0xe977),
  'icon-globe': const FeatherIconData(0xe978),
  'icon-grid': const FeatherIconData(0xe979),
  'icon-hard-drive': const FeatherIconData(0xe97a),
  'icon-hash': const FeatherIconData(0xe97b),
  'icon-headphones': const FeatherIconData(0xe97c),
  'icon-heart': const FeatherIconData(0xe97d),
  'icon-help-circle': const FeatherIconData(0xe97e),
  'icon-hexagon': const FeatherIconData(0xe97f),
  'icon-home': const FeatherIconData(0xe980),
  'icon-image': const FeatherIconData(0xe981),
  'icon-inbox': const FeatherIconData(0xe982),
  'icon-info': const FeatherIconData(0xe983),
  'icon-instagram': const FeatherIconData(0xe984),
  'icon-italic': const FeatherIconData(0xe985),
  'icon-key': const FeatherIconData(0xe986),
  'icon-layers': const FeatherIconData(0xe987),
  'icon-layout': const FeatherIconData(0xe988),
  'icon-life-buoy': const FeatherIconData(0xe989),
  'icon-link': const FeatherIconData(0xe98a),
  'icon-link-2': const FeatherIconData(0xe98b),
  'icon-linkedin': const FeatherIconData(0xe98c),
  'icon-list': const FeatherIconData(0xe98d),
  'icon-loader': const FeatherIconData(0xe98e),
  'icon-lock': const FeatherIconData(0xe98f),
  'icon-log-in': const FeatherIconData(0xe990),
  'icon-log-out': const FeatherIconData(0xe991),
  'icon-mail': const FeatherIconData(0xe992),
  'icon-map': const FeatherIconData(0xe993),
  'icon-map-pin': const FeatherIconData(0xe994),
  'icon-maximize': const FeatherIconData(0xe995),
  'icon-maximize-2': const FeatherIconData(0xe996),
  'icon-meh': const FeatherIconData(0xe997),
  'icon-menu': const FeatherIconData(0xe998),
  'icon-message-circle': const FeatherIconData(0xe999),
  'icon-message-square': const FeatherIconData(0xe99a),
  'icon-mic': const FeatherIconData(0xe99b),
  'icon-mic-off': const FeatherIconData(0xe99c),
  'icon-minimize': const FeatherIconData(0xe99d),
  'icon-minimize-2': const FeatherIconData(0xe99e),
  'icon-minus': const FeatherIconData(0xe99f),
  'icon-minus-circle': const FeatherIconData(0xe9a0),
  'icon-minus-square': const FeatherIconData(0xe9a1),
  'icon-monitor': const FeatherIconData(0xe9a2),
  'icon-moon': const FeatherIconData(0xe9a3),
  'icon-more-horizontal': const FeatherIconData(0xe9a4),
  'icon-more-vertical': const FeatherIconData(0xe9a5),
  'icon-mouse-pointer': const FeatherIconData(0xe9a6),
  'icon-move': const FeatherIconData(0xe9a7),
  'icon-music': const FeatherIconData(0xe9a8),
  'icon-navigation': const FeatherIconData(0xe9a9),
  'icon-navigation-2': const FeatherIconData(0xe9aa),
  'icon-octagon': const FeatherIconData(0xe9ab),
  'icon-package': const FeatherIconData(0xe9ac),
  'icon-paperclip': const FeatherIconData(0xe9ad),
  'icon-pause': const FeatherIconData(0xe9ae),
  'icon-pause-circle': const FeatherIconData(0xe9af),
  'icon-pen-tool': const FeatherIconData(0xe9b0),
  'icon-percent': const FeatherIconData(0xe9b1),
  'icon-phone': const FeatherIconData(0xe9b2),
  'icon-phone-call': const FeatherIconData(0xe9b3),
  'icon-phone-forwarded': const FeatherIconData(0xe9b4),
  'icon-phone-incoming': const FeatherIconData(0xe9b5),
  'icon-phone-missed': const FeatherIconData(0xe9b6),
  'icon-phone-off': const FeatherIconData(0xe9b7),
  'icon-phone-outgoing': const FeatherIconData(0xe9b8),
  'icon-pie-chart': const FeatherIconData(0xe9b9),
  'icon-play': const FeatherIconData(0xe9ba),
  'icon-play-circle': const FeatherIconData(0xe9bb),
  'icon-plus': const FeatherIconData(0xe9bc),
  'icon-plus-circle': const FeatherIconData(0xe9bd),
  'icon-plus-square': const FeatherIconData(0xe9be),
  'icon-pocket': const FeatherIconData(0xe9bf),
  'icon-power': const FeatherIconData(0xe9c0),
  'icon-printer': const FeatherIconData(0xe9c1),
  'icon-radio': const FeatherIconData(0xe9c2),
  'icon-refresh-ccw': const FeatherIconData(0xe9c3),
  'icon-refresh-cw': const FeatherIconData(0xe9c4),
  'icon-repeat': const FeatherIconData(0xe9c5),
  'icon-rewind': const FeatherIconData(0xe9c6),
  'icon-rotate-ccw': const FeatherIconData(0xe9c7),
  'icon-rotate-cw': const FeatherIconData(0xe9c8),
  'icon-rss': const FeatherIconData(0xe9c9),
  'icon-save': const FeatherIconData(0xe9ca),
  'icon-scissors': const FeatherIconData(0xe9cb),
  'icon-search': const FeatherIconData(0xe9cc),
  'icon-send': const FeatherIconData(0xe9cd),
  'icon-server': const FeatherIconData(0xe9ce),
  'icon-settings': const FeatherIconData(0xe9cf),
  'icon-share': const FeatherIconData(0xe9d0),
  'icon-share-2': const FeatherIconData(0xe9d1),
  'icon-shield': const FeatherIconData(0xe9d2),
  'icon-shield-off': const FeatherIconData(0xe9d3),
  'icon-shopping-bag': const FeatherIconData(0xe9d4),
  'icon-shopping-cart': const FeatherIconData(0xe9d5),
  'icon-shuffle': const FeatherIconData(0xe9d6),
  'icon-sidebar': const FeatherIconData(0xe9d7),
  'icon-skip-back': const FeatherIconData(0xe9d8),
  'icon-skip-forward': const FeatherIconData(0xe9d9),
  'icon-slack': const FeatherIconData(0xe9da),
  'icon-slash': const FeatherIconData(0xe9db),
  'icon-sliders': const FeatherIconData(0xe9dc),
  'icon-smartphone': const FeatherIconData(0xe9dd),
  'icon-smile': const FeatherIconData(0xe9de),
  'icon-speaker': const FeatherIconData(0xe9df),
  'icon-square': const FeatherIconData(0xe9e0),
  'icon-star': const FeatherIconData(0xe9e1),
  'icon-stop-circle': const FeatherIconData(0xe9e2),
  'icon-sun': const FeatherIconData(0xe9e3),
  'icon-sunrise': const FeatherIconData(0xe9e4),
  'icon-sunset': const FeatherIconData(0xe9e5),
  'icon-tablet': const FeatherIconData(0xe9e6),
  'icon-tag': const FeatherIconData(0xe9e7),
  'icon-target': const FeatherIconData(0xe9e8),
  'icon-terminal': const FeatherIconData(0xe9e9),
  'icon-thermometer': const FeatherIconData(0xe9ea),
  'icon-thumbs-down': const FeatherIconData(0xe9eb),
  'icon-thumbs-up': const FeatherIconData(0xe9ec),
  'icon-toggle-left': const FeatherIconData(0xe9ed),
  'icon-toggle-right': const FeatherIconData(0xe9ee),
  'icon-tool': const FeatherIconData(0xe9ef),
  'icon-trash': const FeatherIconData(0xe9f0),
  'icon-trash-2': const FeatherIconData(0xe9f1),
  'icon-trello': const FeatherIconData(0xe9f2),
  'icon-trending-down': const FeatherIconData(0xe9f3),
  'icon-trending-up': const FeatherIconData(0xe9f4),
  'icon-triangle': const FeatherIconData(0xe9f5),
  'icon-truck': const FeatherIconData(0xe9f6),
  'icon-tv': const FeatherIconData(0xe9f7),
  'icon-twitch': const FeatherIconData(0xe9f8),
  'icon-twitter': const FeatherIconData(0xe9f9),
  'icon-type': const FeatherIconData(0xe9fa),
  'icon-umbrella': const FeatherIconData(0xe9fb),
  'icon-underline': const FeatherIconData(0xe9fc),
  'icon-unlock': const FeatherIconData(0xe9fd),
  'icon-upload': const FeatherIconData(0xe9fe),
  'icon-upload-cloud': const FeatherIconData(0xe9ff),
  'icon-user': const FeatherIconData(0xea00),
  'icon-user-check': const FeatherIconData(0xea01),
  'icon-user-minus': const FeatherIconData(0xea02),
  'icon-user-plus': const FeatherIconData(0xea03),
  'icon-user-x': const FeatherIconData(0xea04),
  'icon-users': const FeatherIconData(0xea05),
  'icon-video': const FeatherIconData(0xea06),
  'icon-video-off': const FeatherIconData(0xea07),
  'icon-voicemail': const FeatherIconData(0xea08),
  'icon-volume': const FeatherIconData(0xea09),
  'icon-volume-1': const FeatherIconData(0xea0a),
  'icon-volume-2': const FeatherIconData(0xea0b),
  'icon-volume-x': const FeatherIconData(0xea0c),
  'icon-watch': const FeatherIconData(0xea0d),
  'icon-wifi': const FeatherIconData(0xea0e),
  'icon-wifi-off': const FeatherIconData(0xea0f),
  'icon-wind': const FeatherIconData(0xea10),
  'icon-x': const FeatherIconData(0xea11),
  'icon-x-circle': const FeatherIconData(0xea12),
  'icon-x-octagon': const FeatherIconData(0xea13),
  'icon-x-square': const FeatherIconData(0xea14),
  'icon-youtube': const FeatherIconData(0xea15),
  'icon-zap': const FeatherIconData(0xea16),
  'icon-zap-off': const FeatherIconData(0xea17),
  'icon-zoom-in': const FeatherIconData(0xea18),
  'icon-zoom-out': const FeatherIconData(0xea19),
};

class FeatherIcons {
  static const IconData iconActivity = const FeatherIconData(0xe900);
  static const IconData iconAirplay = const FeatherIconData(0xe901);
  static const IconData iconAlertCircle = const FeatherIconData(0xe902);
  static const IconData iconAlertOctagon = const FeatherIconData(0xe903);
  static const IconData iconAlertTriangle = const FeatherIconData(0xe904);
  static const IconData iconAlignCenter = const FeatherIconData(0xe905);
  static const IconData iconAlignJustify = const FeatherIconData(0xe906);
  static const IconData iconAlignLeft = const FeatherIconData(0xe907);
  static const IconData iconAlignRight = const FeatherIconData(0xe908);
  static const IconData iconAnchor = const FeatherIconData(0xe909);
  static const IconData iconAperture = const FeatherIconData(0xe90a);
  static const IconData iconArchive = const FeatherIconData(0xe90b);
  static const IconData iconArrowDown = const FeatherIconData(0xe90c);
  static const IconData iconArrowDownCircle = const FeatherIconData(0xe90d);
  static const IconData iconArrowDownLeft = const FeatherIconData(0xe90e);
  static const IconData iconArrowDownRight = const FeatherIconData(0xe90f);
  static const IconData iconArrowLeft = const FeatherIconData(0xe910);
  static const IconData iconArrowLeftCircle = const FeatherIconData(0xe911);
  static const IconData iconArrowRight = const FeatherIconData(0xe912);
  static const IconData iconArrowRightCircle = const FeatherIconData(0xe913);
  static const IconData iconArrowUp = const FeatherIconData(0xe914);
  static const IconData iconArrowUpCircle = const FeatherIconData(0xe915);
  static const IconData iconArrowUpLeft = const FeatherIconData(0xe916);
  static const IconData iconArrowUpRight = const FeatherIconData(0xe917);
  static const IconData iconAtSign = const FeatherIconData(0xe918);
  static const IconData iconAward = const FeatherIconData(0xe919);
  static const IconData iconBarChart = const FeatherIconData(0xe91a);
  static const IconData iconBarChart2 = const FeatherIconData(0xe91b);
  static const IconData iconBattery = const FeatherIconData(0xe91c);
  static const IconData iconBatteryCharging = const FeatherIconData(0xe91d);
  static const IconData iconBell = const FeatherIconData(0xe91e);
  static const IconData iconBellOff = const FeatherIconData(0xe91f);
  static const IconData iconBluetooth = const FeatherIconData(0xe920);
  static const IconData iconBold = const FeatherIconData(0xe921);
  static const IconData iconBook = const FeatherIconData(0xe922);
  static const IconData iconBookOpen = const FeatherIconData(0xe923);
  static const IconData iconBookmark = const FeatherIconData(0xe924);
  static const IconData iconBox = const FeatherIconData(0xe925);
  static const IconData iconBriefcase = const FeatherIconData(0xe926);
  static const IconData iconCalendar = const FeatherIconData(0xe927);
  static const IconData iconCamera = const FeatherIconData(0xe928);
  static const IconData iconCameraOff = const FeatherIconData(0xe929);
  static const IconData iconCast = const FeatherIconData(0xe92a);
  static const IconData iconCheck = const FeatherIconData(0xe92b);
  static const IconData iconCheckCircle = const FeatherIconData(0xe92c);
  static const IconData iconCheckSquare = const FeatherIconData(0xe92d);
  static const IconData iconChevronDown = const FeatherIconData(0xe92e);
  static const IconData iconChevronLeft = const FeatherIconData(0xe92f);
  static const IconData iconChevronRight = const FeatherIconData(0xe930);
  static const IconData iconChevronUp = const FeatherIconData(0xe931);
  static const IconData iconChevronsDown = const FeatherIconData(0xe932);
  static const IconData iconChevronsLeft = const FeatherIconData(0xe933);
  static const IconData iconChevronsRight = const FeatherIconData(0xe934);
  static const IconData iconChevronsUp = const FeatherIconData(0xe935);
  static const IconData iconChrome = const FeatherIconData(0xe936);
  static const IconData iconCircle = const FeatherIconData(0xe937);
  static const IconData iconClipboard = const FeatherIconData(0xe938);
  static const IconData iconClock = const FeatherIconData(0xe939);
  static const IconData iconCloud = const FeatherIconData(0xe93a);
  static const IconData iconCloudDrizzle = const FeatherIconData(0xe93b);
  static const IconData iconCloudLightning = const FeatherIconData(0xe93c);
  static const IconData iconCloudOff = const FeatherIconData(0xe93d);
  static const IconData iconCloudRain = const FeatherIconData(0xe93e);
  static const IconData iconCloudSnow = const FeatherIconData(0xe93f);
  static const IconData iconCode = const FeatherIconData(0xe940);
  static const IconData iconCodepen = const FeatherIconData(0xe941);
  static const IconData iconCodesandbox = const FeatherIconData(0xe942);
  static const IconData iconCoffee = const FeatherIconData(0xe943);
  static const IconData iconColumns = const FeatherIconData(0xe944);
  static const IconData iconCommand = const FeatherIconData(0xe945);
  static const IconData iconCompass = const FeatherIconData(0xe946);
  static const IconData iconCopy = const FeatherIconData(0xe947);
  static const IconData iconCornerDownLeft = const FeatherIconData(0xe948);
  static const IconData iconCornerDownRight = const FeatherIconData(0xe949);
  static const IconData iconCornerLeftDown = const FeatherIconData(0xe94a);
  static const IconData iconCornerLeftUp = const FeatherIconData(0xe94b);
  static const IconData iconCornerRightDown = const FeatherIconData(0xe94c);
  static const IconData iconCornerRightUp = const FeatherIconData(0xe94d);
  static const IconData iconCornerUpLeft = const FeatherIconData(0xe94e);
  static const IconData iconCornerUpRight = const FeatherIconData(0xe94f);
  static const IconData iconCpu = const FeatherIconData(0xe950);
  static const IconData iconCreditCard = const FeatherIconData(0xe951);
  static const IconData iconCrop = const FeatherIconData(0xe952);
  static const IconData iconCrosshair = const FeatherIconData(0xe953);
  static const IconData iconDatabase = const FeatherIconData(0xe954);
  static const IconData iconDelete = const FeatherIconData(0xe955);
  static const IconData iconDisc = const FeatherIconData(0xe956);
  static const IconData iconDollarSign = const FeatherIconData(0xe957);
  static const IconData iconDownload = const FeatherIconData(0xe958);
  static const IconData iconDownloadCloud = const FeatherIconData(0xe959);
  static const IconData iconDroplet = const FeatherIconData(0xe95a);
  static const IconData iconEdit = const FeatherIconData(0xe95b);
  static const IconData iconEdit2 = const FeatherIconData(0xe95c);
  static const IconData iconEdit3 = const FeatherIconData(0xe95d);
  static const IconData iconExternalLink = const FeatherIconData(0xe95e);
  static const IconData iconEye = const FeatherIconData(0xe95f);
  static const IconData iconEyeOff = const FeatherIconData(0xe960);
  static const IconData iconFacebook = const FeatherIconData(0xe961);
  static const IconData iconFastForward = const FeatherIconData(0xe962);
  static const IconData iconFeather = const FeatherIconData(0xe963);
  static const IconData iconFigma = const FeatherIconData(0xe964);
  static const IconData iconFile = const FeatherIconData(0xe965);
  static const IconData iconFileMinus = const FeatherIconData(0xe966);
  static const IconData iconFilePlus = const FeatherIconData(0xe967);
  static const IconData iconFileText = const FeatherIconData(0xe968);
  static const IconData iconFilm = const FeatherIconData(0xe969);
  static const IconData iconFilter = const FeatherIconData(0xe96a);
  static const IconData iconFlag = const FeatherIconData(0xe96b);
  static const IconData iconFolder = const FeatherIconData(0xe96c);
  static const IconData iconFolderMinus = const FeatherIconData(0xe96d);
  static const IconData iconFolderPlus = const FeatherIconData(0xe96e);
  static const IconData iconFramer = const FeatherIconData(0xe96f);
  static const IconData iconFrown = const FeatherIconData(0xe970);
  static const IconData iconGift = const FeatherIconData(0xe971);
  static const IconData iconGitBranch = const FeatherIconData(0xe972);
  static const IconData iconGitCommit = const FeatherIconData(0xe973);
  static const IconData iconGitMerge = const FeatherIconData(0xe974);
  static const IconData iconGitPullRequest = const FeatherIconData(0xe975);
  static const IconData iconGithub = const FeatherIconData(0xe976);
  static const IconData iconGitlab = const FeatherIconData(0xe977);
  static const IconData iconGlobe = const FeatherIconData(0xe978);
  static const IconData iconGrid = const FeatherIconData(0xe979);
  static const IconData iconHardDrive = const FeatherIconData(0xe97a);
  static const IconData iconHash = const FeatherIconData(0xe97b);
  static const IconData iconHeadphones = const FeatherIconData(0xe97c);
  static const IconData iconHeart = const FeatherIconData(0xe97d);
  static const IconData iconHelpCircle = const FeatherIconData(0xe97e);
  static const IconData iconHexagon = const FeatherIconData(0xe97f);
  static const IconData iconHome = const FeatherIconData(0xe980);
  static const IconData iconImage = const FeatherIconData(0xe981);
  static const IconData iconInbox = const FeatherIconData(0xe982);
  static const IconData iconInfo = const FeatherIconData(0xe983);
  static const IconData iconInstagram = const FeatherIconData(0xe984);
  static const IconData iconItalic = const FeatherIconData(0xe985);
  static const IconData iconKey = const FeatherIconData(0xe986);
  static const IconData iconLayers = const FeatherIconData(0xe987);
  static const IconData iconLayout = const FeatherIconData(0xe988);
  static const IconData iconLifeBuoy = const FeatherIconData(0xe989);
  static const IconData iconLink = const FeatherIconData(0xe98a);
  static const IconData iconLink2 = const FeatherIconData(0xe98b);
  static const IconData iconLinkedin = const FeatherIconData(0xe98c);
  static const IconData iconList = const FeatherIconData(0xe98d);
  static const IconData iconLoader = const FeatherIconData(0xe98e);
  static const IconData iconLock = const FeatherIconData(0xe98f);
  static const IconData iconLogIn = const FeatherIconData(0xe990);
  static const IconData iconLogOut = const FeatherIconData(0xe991);
  static const IconData iconMail = const FeatherIconData(0xe992);
  static const IconData iconMap = const FeatherIconData(0xe993);
  static const IconData iconMapPin = const FeatherIconData(0xe994);
  static const IconData iconMaximize = const FeatherIconData(0xe995);
  static const IconData iconMaximize2 = const FeatherIconData(0xe996);
  static const IconData iconMeh = const FeatherIconData(0xe997);
  static const IconData iconMenu = const FeatherIconData(0xe998);
  static const IconData iconMessageCircle = const FeatherIconData(0xe999);
  static const IconData iconMessageSquare = const FeatherIconData(0xe99a);
  static const IconData iconMic = const FeatherIconData(0xe99b);
  static const IconData iconMicOff = const FeatherIconData(0xe99c);
  static const IconData iconMinimize = const FeatherIconData(0xe99d);
  static const IconData iconMinimize2 = const FeatherIconData(0xe99e);
  static const IconData iconMinus = const FeatherIconData(0xe99f);
  static const IconData iconMinusCircle = const FeatherIconData(0xe9a0);
  static const IconData iconMinusSquare = const FeatherIconData(0xe9a1);
  static const IconData iconMonitor = const FeatherIconData(0xe9a2);
  static const IconData iconMoon = const FeatherIconData(0xe9a3);
  static const IconData iconMoreHorizontal = const FeatherIconData(0xe9a4);
  static const IconData iconMoreVertical = const FeatherIconData(0xe9a5);
  static const IconData iconMousePointer = const FeatherIconData(0xe9a6);
  static const IconData iconMove = const FeatherIconData(0xe9a7);
  static const IconData iconMusic = const FeatherIconData(0xe9a8);
  static const IconData iconNavigation = const FeatherIconData(0xe9a9);
  static const IconData iconNavigation2 = const FeatherIconData(0xe9aa);
  static const IconData iconOctagon = const FeatherIconData(0xe9ab);
  static const IconData iconPackage = const FeatherIconData(0xe9ac);
  static const IconData iconPaperclip = const FeatherIconData(0xe9ad);
  static const IconData iconPause = const FeatherIconData(0xe9ae);
  static const IconData iconPauseCircle = const FeatherIconData(0xe9af);
  static const IconData iconPenTool = const FeatherIconData(0xe9b0);
  static const IconData iconPercent = const FeatherIconData(0xe9b1);
  static const IconData iconPhone = const FeatherIconData(0xe9b2);
  static const IconData iconPhoneCall = const FeatherIconData(0xe9b3);
  static const IconData iconPhoneForwarded = const FeatherIconData(0xe9b4);
  static const IconData iconPhoneIncoming = const FeatherIconData(0xe9b5);
  static const IconData iconPhoneMissed = const FeatherIconData(0xe9b6);
  static const IconData iconPhoneOff = const FeatherIconData(0xe9b7);
  static const IconData iconPhoneOutgoing = const FeatherIconData(0xe9b8);
  static const IconData iconPieChart = const FeatherIconData(0xe9b9);
  static const IconData iconPlay = const FeatherIconData(0xe9ba);
  static const IconData iconPlayCircle = const FeatherIconData(0xe9bb);
  static const IconData iconPlus = const FeatherIconData(0xe9bc);
  static const IconData iconPlusCircle = const FeatherIconData(0xe9bd);
  static const IconData iconPlusSquare = const FeatherIconData(0xe9be);
  static const IconData iconPocket = const FeatherIconData(0xe9bf);
  static const IconData iconPower = const FeatherIconData(0xe9c0);
  static const IconData iconPrinter = const FeatherIconData(0xe9c1);
  static const IconData iconRadio = const FeatherIconData(0xe9c2);
  static const IconData iconRefreshCcw = const FeatherIconData(0xe9c3);
  static const IconData iconRefreshCw = const FeatherIconData(0xe9c4);
  static const IconData iconRepeat = const FeatherIconData(0xe9c5);
  static const IconData iconRewind = const FeatherIconData(0xe9c6);
  static const IconData iconRotateCcw = const FeatherIconData(0xe9c7);
  static const IconData iconRotateCw = const FeatherIconData(0xe9c8);
  static const IconData iconRss = const FeatherIconData(0xe9c9);
  static const IconData iconSave = const FeatherIconData(0xe9ca);
  static const IconData iconScissors = const FeatherIconData(0xe9cb);
  static const IconData iconSearch = const FeatherIconData(0xe9cc);
  static const IconData iconSend = const FeatherIconData(0xe9cd);
  static const IconData iconServer = const FeatherIconData(0xe9ce);
  static const IconData iconSettings = const FeatherIconData(0xe9cf);
  static const IconData iconShare = const FeatherIconData(0xe9d0);
  static const IconData iconShare2 = const FeatherIconData(0xe9d1);
  static const IconData iconShield = const FeatherIconData(0xe9d2);
  static const IconData iconShieldOff = const FeatherIconData(0xe9d3);
  static const IconData iconShoppingBag = const FeatherIconData(0xe9d4);
  static const IconData iconShoppingCart = const FeatherIconData(0xe9d5);
  static const IconData iconShuffle = const FeatherIconData(0xe9d6);
  static const IconData iconSidebar = const FeatherIconData(0xe9d7);
  static const IconData iconSkipBack = const FeatherIconData(0xe9d8);
  static const IconData iconSkipForward = const FeatherIconData(0xe9d9);
  static const IconData iconSlack = const FeatherIconData(0xe9da);
  static const IconData iconSlash = const FeatherIconData(0xe9db);
  static const IconData iconSliders = const FeatherIconData(0xe9dc);
  static const IconData iconSmartphone = const FeatherIconData(0xe9dd);
  static const IconData iconSmile = const FeatherIconData(0xe9de);
  static const IconData iconSpeaker = const FeatherIconData(0xe9df);
  static const IconData iconSquare = const FeatherIconData(0xe9e0);
  static const IconData iconStar = const FeatherIconData(0xe9e1);
  static const IconData iconStopCircle = const FeatherIconData(0xe9e2);
  static const IconData iconSun = const FeatherIconData(0xe9e3);
  static const IconData iconSunrise = const FeatherIconData(0xe9e4);
  static const IconData iconSunset = const FeatherIconData(0xe9e5);
  static const IconData iconTablet = const FeatherIconData(0xe9e6);
  static const IconData iconTag = const FeatherIconData(0xe9e7);
  static const IconData iconTarget = const FeatherIconData(0xe9e8);
  static const IconData iconTerminal = const FeatherIconData(0xe9e9);
  static const IconData iconThermometer = const FeatherIconData(0xe9ea);
  static const IconData iconThumbsDown = const FeatherIconData(0xe9eb);
  static const IconData iconThumbsUp = const FeatherIconData(0xe9ec);
  static const IconData iconToggleLeft = const FeatherIconData(0xe9ed);
  static const IconData iconToggleRight = const FeatherIconData(0xe9ee);
  static const IconData iconTool = const FeatherIconData(0xe9ef);
  static const IconData iconTrash = const FeatherIconData(0xe9f0);
  static const IconData iconTrash2 = const FeatherIconData(0xe9f1);
  static const IconData iconTrello = const FeatherIconData(0xe9f2);
  static const IconData iconTrendingDown = const FeatherIconData(0xe9f3);
  static const IconData iconTrendingUp = const FeatherIconData(0xe9f4);
  static const IconData iconTriangle = const FeatherIconData(0xe9f5);
  static const IconData iconTruck = const FeatherIconData(0xe9f6);
  static const IconData iconTv = const FeatherIconData(0xe9f7);
  static const IconData iconTwitch = const FeatherIconData(0xe9f8);
  static const IconData iconTwitter = const FeatherIconData(0xe9f9);
  static const IconData iconType = const FeatherIconData(0xe9fa);
  static const IconData iconUmbrella = const FeatherIconData(0xe9fb);
  static const IconData iconUnderline = const FeatherIconData(0xe9fc);
  static const IconData iconUnlock = const FeatherIconData(0xe9fd);
  static const IconData iconUpload = const FeatherIconData(0xe9fe);
  static const IconData iconUploadCloud = const FeatherIconData(0xe9ff);
  static const IconData iconUser = const FeatherIconData(0xea00);
  static const IconData iconUserCheck = const FeatherIconData(0xea01);
  static const IconData iconUserMinus = const FeatherIconData(0xea02);
  static const IconData iconUserPlus = const FeatherIconData(0xea03);
  static const IconData iconUserX = const FeatherIconData(0xea04);
  static const IconData iconUsers = const FeatherIconData(0xea05);
  static const IconData iconVideo = const FeatherIconData(0xea06);
  static const IconData iconVideoOff = const FeatherIconData(0xea07);
  static const IconData iconVoicemail = const FeatherIconData(0xea08);
  static const IconData iconVolume = const FeatherIconData(0xea09);
  static const IconData iconVolume1 = const FeatherIconData(0xea0a);
  static const IconData iconVolume2 = const FeatherIconData(0xea0b);
  static const IconData iconVolumeX = const FeatherIconData(0xea0c);
  static const IconData iconWatch = const FeatherIconData(0xea0d);
  static const IconData iconWifi = const FeatherIconData(0xea0e);
  static const IconData iconWifiOff = const FeatherIconData(0xea0f);
  static const IconData iconWind = const FeatherIconData(0xea10);
  static const IconData iconX = const FeatherIconData(0xea11);
  static const IconData iconXCircle = const FeatherIconData(0xea12);
  static const IconData iconXOctagon = const FeatherIconData(0xea13);
  static const IconData iconXSquare = const FeatherIconData(0xea14);
  static const IconData iconYoutube = const FeatherIconData(0xea15);
  static const IconData iconZap = const FeatherIconData(0xea16);
  static const IconData iconZapOff = const FeatherIconData(0xea17);
  static const IconData iconZoomIn = const FeatherIconData(0xea18);
  static const IconData iconZoomOut = const FeatherIconData(0xea19);
}

class FeatherIconsSnakeCase {
  static const IconData icon_activity = const FeatherIconData(0xe900);
  static const IconData icon_airplay = const FeatherIconData(0xe901);
  static const IconData icon_alert_circle = const FeatherIconData(0xe902);
  static const IconData icon_alert_octagon = const FeatherIconData(0xe903);
  static const IconData icon_alert_triangle = const FeatherIconData(0xe904);
  static const IconData icon_align_center = const FeatherIconData(0xe905);
  static const IconData icon_align_justify = const FeatherIconData(0xe906);
  static const IconData icon_align_left = const FeatherIconData(0xe907);
  static const IconData icon_align_right = const FeatherIconData(0xe908);
  static const IconData icon_anchor = const FeatherIconData(0xe909);
  static const IconData icon_aperture = const FeatherIconData(0xe90a);
  static const IconData icon_archive = const FeatherIconData(0xe90b);
  static const IconData icon_arrow_down = const FeatherIconData(0xe90c);
  static const IconData icon_arrow_down_circle = const FeatherIconData(0xe90d);
  static const IconData icon_arrow_down_left = const FeatherIconData(0xe90e);
  static const IconData icon_arrow_down_right = const FeatherIconData(0xe90f);
  static const IconData icon_arrow_left = const FeatherIconData(0xe910);
  static const IconData icon_arrow_left_circle = const FeatherIconData(0xe911);
  static const IconData icon_arrow_right = const FeatherIconData(0xe912);
  static const IconData icon_arrow_right_circle = const FeatherIconData(0xe913);
  static const IconData icon_arrow_up = const FeatherIconData(0xe914);
  static const IconData icon_arrow_up_circle = const FeatherIconData(0xe915);
  static const IconData icon_arrow_up_left = const FeatherIconData(0xe916);
  static const IconData icon_arrow_up_right = const FeatherIconData(0xe917);
  static const IconData icon_at_sign = const FeatherIconData(0xe918);
  static const IconData icon_award = const FeatherIconData(0xe919);
  static const IconData icon_bar_chart = const FeatherIconData(0xe91a);
  static const IconData icon_bar_chart_2 = const FeatherIconData(0xe91b);
  static const IconData icon_battery = const FeatherIconData(0xe91c);
  static const IconData icon_battery_charging = const FeatherIconData(0xe91d);
  static const IconData icon_bell = const FeatherIconData(0xe91e);
  static const IconData icon_bell_off = const FeatherIconData(0xe91f);
  static const IconData icon_bluetooth = const FeatherIconData(0xe920);
  static const IconData icon_bold = const FeatherIconData(0xe921);
  static const IconData icon_book = const FeatherIconData(0xe922);
  static const IconData icon_book_open = const FeatherIconData(0xe923);
  static const IconData icon_bookmark = const FeatherIconData(0xe924);
  static const IconData icon_box = const FeatherIconData(0xe925);
  static const IconData icon_briefcase = const FeatherIconData(0xe926);
  static const IconData icon_calendar = const FeatherIconData(0xe927);
  static const IconData icon_camera = const FeatherIconData(0xe928);
  static const IconData icon_camera_off = const FeatherIconData(0xe929);
  static const IconData icon_cast = const FeatherIconData(0xe92a);
  static const IconData icon_check = const FeatherIconData(0xe92b);
  static const IconData icon_check_circle = const FeatherIconData(0xe92c);
  static const IconData icon_check_square = const FeatherIconData(0xe92d);
  static const IconData icon_chevron_down = const FeatherIconData(0xe92e);
  static const IconData icon_chevron_left = const FeatherIconData(0xe92f);
  static const IconData icon_chevron_right = const FeatherIconData(0xe930);
  static const IconData icon_chevron_up = const FeatherIconData(0xe931);
  static const IconData icon_chevrons_down = const FeatherIconData(0xe932);
  static const IconData icon_chevrons_left = const FeatherIconData(0xe933);
  static const IconData icon_chevrons_right = const FeatherIconData(0xe934);
  static const IconData icon_chevrons_up = const FeatherIconData(0xe935);
  static const IconData icon_chrome = const FeatherIconData(0xe936);
  static const IconData icon_circle = const FeatherIconData(0xe937);
  static const IconData icon_clipboard = const FeatherIconData(0xe938);
  static const IconData icon_clock = const FeatherIconData(0xe939);
  static const IconData icon_cloud = const FeatherIconData(0xe93a);
  static const IconData icon_cloud_drizzle = const FeatherIconData(0xe93b);
  static const IconData icon_cloud_lightning = const FeatherIconData(0xe93c);
  static const IconData icon_cloud_off = const FeatherIconData(0xe93d);
  static const IconData icon_cloud_rain = const FeatherIconData(0xe93e);
  static const IconData icon_cloud_snow = const FeatherIconData(0xe93f);
  static const IconData icon_code = const FeatherIconData(0xe940);
  static const IconData icon_codepen = const FeatherIconData(0xe941);
  static const IconData icon_codesandbox = const FeatherIconData(0xe942);
  static const IconData icon_coffee = const FeatherIconData(0xe943);
  static const IconData icon_columns = const FeatherIconData(0xe944);
  static const IconData icon_command = const FeatherIconData(0xe945);
  static const IconData icon_compass = const FeatherIconData(0xe946);
  static const IconData icon_copy = const FeatherIconData(0xe947);
  static const IconData icon_corner_down_left = const FeatherIconData(0xe948);
  static const IconData icon_corner_down_right = const FeatherIconData(0xe949);
  static const IconData icon_corner_left_down = const FeatherIconData(0xe94a);
  static const IconData icon_corner_left_up = const FeatherIconData(0xe94b);
  static const IconData icon_corner_right_down = const FeatherIconData(0xe94c);
  static const IconData icon_corner_right_up = const FeatherIconData(0xe94d);
  static const IconData icon_corner_up_left = const FeatherIconData(0xe94e);
  static const IconData icon_corner_up_right = const FeatherIconData(0xe94f);
  static const IconData icon_cpu = const FeatherIconData(0xe950);
  static const IconData icon_credit_card = const FeatherIconData(0xe951);
  static const IconData icon_crop = const FeatherIconData(0xe952);
  static const IconData icon_crosshair = const FeatherIconData(0xe953);
  static const IconData icon_database = const FeatherIconData(0xe954);
  static const IconData icon_delete = const FeatherIconData(0xe955);
  static const IconData icon_disc = const FeatherIconData(0xe956);
  static const IconData icon_dollar_sign = const FeatherIconData(0xe957);
  static const IconData icon_download = const FeatherIconData(0xe958);
  static const IconData icon_download_cloud = const FeatherIconData(0xe959);
  static const IconData icon_droplet = const FeatherIconData(0xe95a);
  static const IconData icon_edit = const FeatherIconData(0xe95b);
  static const IconData icon_edit_2 = const FeatherIconData(0xe95c);
  static const IconData icon_edit_3 = const FeatherIconData(0xe95d);
  static const IconData icon_external_link = const FeatherIconData(0xe95e);
  static const IconData icon_eye = const FeatherIconData(0xe95f);
  static const IconData icon_eye_off = const FeatherIconData(0xe960);
  static const IconData icon_facebook = const FeatherIconData(0xe961);
  static const IconData icon_fast_forward = const FeatherIconData(0xe962);
  static const IconData icon_feather = const FeatherIconData(0xe963);
  static const IconData icon_figma = const FeatherIconData(0xe964);
  static const IconData icon_file = const FeatherIconData(0xe965);
  static const IconData icon_file_minus = const FeatherIconData(0xe966);
  static const IconData icon_file_plus = const FeatherIconData(0xe967);
  static const IconData icon_file_text = const FeatherIconData(0xe968);
  static const IconData icon_film = const FeatherIconData(0xe969);
  static const IconData icon_filter = const FeatherIconData(0xe96a);
  static const IconData icon_flag = const FeatherIconData(0xe96b);
  static const IconData icon_folder = const FeatherIconData(0xe96c);
  static const IconData icon_folder_minus = const FeatherIconData(0xe96d);
  static const IconData icon_folder_plus = const FeatherIconData(0xe96e);
  static const IconData icon_framer = const FeatherIconData(0xe96f);
  static const IconData icon_frown = const FeatherIconData(0xe970);
  static const IconData icon_gift = const FeatherIconData(0xe971);
  static const IconData icon_git_branch = const FeatherIconData(0xe972);
  static const IconData icon_git_commit = const FeatherIconData(0xe973);
  static const IconData icon_git_merge = const FeatherIconData(0xe974);
  static const IconData icon_git_pull_request = const FeatherIconData(0xe975);
  static const IconData icon_github = const FeatherIconData(0xe976);
  static const IconData icon_gitlab = const FeatherIconData(0xe977);
  static const IconData icon_globe = const FeatherIconData(0xe978);
  static const IconData icon_grid = const FeatherIconData(0xe979);
  static const IconData icon_hard_drive = const FeatherIconData(0xe97a);
  static const IconData icon_hash = const FeatherIconData(0xe97b);
  static const IconData icon_headphones = const FeatherIconData(0xe97c);
  static const IconData icon_heart = const FeatherIconData(0xe97d);
  static const IconData icon_help_circle = const FeatherIconData(0xe97e);
  static const IconData icon_hexagon = const FeatherIconData(0xe97f);
  static const IconData icon_home = const FeatherIconData(0xe980);
  static const IconData icon_image = const FeatherIconData(0xe981);
  static const IconData icon_inbox = const FeatherIconData(0xe982);
  static const IconData icon_info = const FeatherIconData(0xe983);
  static const IconData icon_instagram = const FeatherIconData(0xe984);
  static const IconData icon_italic = const FeatherIconData(0xe985);
  static const IconData icon_key = const FeatherIconData(0xe986);
  static const IconData icon_layers = const FeatherIconData(0xe987);
  static const IconData icon_layout = const FeatherIconData(0xe988);
  static const IconData icon_life_buoy = const FeatherIconData(0xe989);
  static const IconData icon_link = const FeatherIconData(0xe98a);
  static const IconData icon_link_2 = const FeatherIconData(0xe98b);
  static const IconData icon_linkedin = const FeatherIconData(0xe98c);
  static const IconData icon_list = const FeatherIconData(0xe98d);
  static const IconData icon_loader = const FeatherIconData(0xe98e);
  static const IconData icon_lock = const FeatherIconData(0xe98f);
  static const IconData icon_log_in = const FeatherIconData(0xe990);
  static const IconData icon_log_out = const FeatherIconData(0xe991);
  static const IconData icon_mail = const FeatherIconData(0xe992);
  static const IconData icon_map = const FeatherIconData(0xe993);
  static const IconData icon_map_pin = const FeatherIconData(0xe994);
  static const IconData icon_maximize = const FeatherIconData(0xe995);
  static const IconData icon_maximize_2 = const FeatherIconData(0xe996);
  static const IconData icon_meh = const FeatherIconData(0xe997);
  static const IconData icon_menu = const FeatherIconData(0xe998);
  static const IconData icon_message_circle = const FeatherIconData(0xe999);
  static const IconData icon_message_square = const FeatherIconData(0xe99a);
  static const IconData icon_mic = const FeatherIconData(0xe99b);
  static const IconData icon_mic_off = const FeatherIconData(0xe99c);
  static const IconData icon_minimize = const FeatherIconData(0xe99d);
  static const IconData icon_minimize_2 = const FeatherIconData(0xe99e);
  static const IconData icon_minus = const FeatherIconData(0xe99f);
  static const IconData icon_minus_circle = const FeatherIconData(0xe9a0);
  static const IconData icon_minus_square = const FeatherIconData(0xe9a1);
  static const IconData icon_monitor = const FeatherIconData(0xe9a2);
  static const IconData icon_moon = const FeatherIconData(0xe9a3);
  static const IconData icon_more_horizontal = const FeatherIconData(0xe9a4);
  static const IconData icon_more_vertical = const FeatherIconData(0xe9a5);
  static const IconData icon_mouse_pointer = const FeatherIconData(0xe9a6);
  static const IconData icon_move = const FeatherIconData(0xe9a7);
  static const IconData icon_music = const FeatherIconData(0xe9a8);
  static const IconData icon_navigation = const FeatherIconData(0xe9a9);
  static const IconData icon_navigation_2 = const FeatherIconData(0xe9aa);
  static const IconData icon_octagon = const FeatherIconData(0xe9ab);
  static const IconData icon_package = const FeatherIconData(0xe9ac);
  static const IconData icon_paperclip = const FeatherIconData(0xe9ad);
  static const IconData icon_pause = const FeatherIconData(0xe9ae);
  static const IconData icon_pause_circle = const FeatherIconData(0xe9af);
  static const IconData icon_pen_tool = const FeatherIconData(0xe9b0);
  static const IconData icon_percent = const FeatherIconData(0xe9b1);
  static const IconData icon_phone = const FeatherIconData(0xe9b2);
  static const IconData icon_phone_call = const FeatherIconData(0xe9b3);
  static const IconData icon_phone_forwarded = const FeatherIconData(0xe9b4);
  static const IconData icon_phone_incoming = const FeatherIconData(0xe9b5);
  static const IconData icon_phone_missed = const FeatherIconData(0xe9b6);
  static const IconData icon_phone_off = const FeatherIconData(0xe9b7);
  static const IconData icon_phone_outgoing = const FeatherIconData(0xe9b8);
  static const IconData icon_pie_chart = const FeatherIconData(0xe9b9);
  static const IconData icon_play = const FeatherIconData(0xe9ba);
  static const IconData icon_play_circle = const FeatherIconData(0xe9bb);
  static const IconData icon_plus = const FeatherIconData(0xe9bc);
  static const IconData icon_plus_circle = const FeatherIconData(0xe9bd);
  static const IconData icon_plus_square = const FeatherIconData(0xe9be);
  static const IconData icon_pocket = const FeatherIconData(0xe9bf);
  static const IconData icon_power = const FeatherIconData(0xe9c0);
  static const IconData icon_printer = const FeatherIconData(0xe9c1);
  static const IconData icon_radio = const FeatherIconData(0xe9c2);
  static const IconData icon_refresh_ccw = const FeatherIconData(0xe9c3);
  static const IconData icon_refresh_cw = const FeatherIconData(0xe9c4);
  static const IconData icon_repeat = const FeatherIconData(0xe9c5);
  static const IconData icon_rewind = const FeatherIconData(0xe9c6);
  static const IconData icon_rotate_ccw = const FeatherIconData(0xe9c7);
  static const IconData icon_rotate_cw = const FeatherIconData(0xe9c8);
  static const IconData icon_rss = const FeatherIconData(0xe9c9);
  static const IconData icon_save = const FeatherIconData(0xe9ca);
  static const IconData icon_scissors = const FeatherIconData(0xe9cb);
  static const IconData icon_search = const FeatherIconData(0xe9cc);
  static const IconData icon_send = const FeatherIconData(0xe9cd);
  static const IconData icon_server = const FeatherIconData(0xe9ce);
  static const IconData icon_settings = const FeatherIconData(0xe9cf);
  static const IconData icon_share = const FeatherIconData(0xe9d0);
  static const IconData icon_share_2 = const FeatherIconData(0xe9d1);
  static const IconData icon_shield = const FeatherIconData(0xe9d2);
  static const IconData icon_shield_off = const FeatherIconData(0xe9d3);
  static const IconData icon_shopping_bag = const FeatherIconData(0xe9d4);
  static const IconData icon_shopping_cart = const FeatherIconData(0xe9d5);
  static const IconData icon_shuffle = const FeatherIconData(0xe9d6);
  static const IconData icon_sidebar = const FeatherIconData(0xe9d7);
  static const IconData icon_skip_back = const FeatherIconData(0xe9d8);
  static const IconData icon_skip_forward = const FeatherIconData(0xe9d9);
  static const IconData icon_slack = const FeatherIconData(0xe9da);
  static const IconData icon_slash = const FeatherIconData(0xe9db);
  static const IconData icon_sliders = const FeatherIconData(0xe9dc);
  static const IconData icon_smartphone = const FeatherIconData(0xe9dd);
  static const IconData icon_smile = const FeatherIconData(0xe9de);
  static const IconData icon_speaker = const FeatherIconData(0xe9df);
  static const IconData icon_square = const FeatherIconData(0xe9e0);
  static const IconData icon_star = const FeatherIconData(0xe9e1);
  static const IconData icon_stop_circle = const FeatherIconData(0xe9e2);
  static const IconData icon_sun = const FeatherIconData(0xe9e3);
  static const IconData icon_sunrise = const FeatherIconData(0xe9e4);
  static const IconData icon_sunset = const FeatherIconData(0xe9e5);
  static const IconData icon_tablet = const FeatherIconData(0xe9e6);
  static const IconData icon_tag = const FeatherIconData(0xe9e7);
  static const IconData icon_target = const FeatherIconData(0xe9e8);
  static const IconData icon_terminal = const FeatherIconData(0xe9e9);
  static const IconData icon_thermometer = const FeatherIconData(0xe9ea);
  static const IconData icon_thumbs_down = const FeatherIconData(0xe9eb);
  static const IconData icon_thumbs_up = const FeatherIconData(0xe9ec);
  static const IconData icon_toggle_left = const FeatherIconData(0xe9ed);
  static const IconData icon_toggle_right = const FeatherIconData(0xe9ee);
  static const IconData icon_tool = const FeatherIconData(0xe9ef);
  static const IconData icon_trash = const FeatherIconData(0xe9f0);
  static const IconData icon_trash_2 = const FeatherIconData(0xe9f1);
  static const IconData icon_trello = const FeatherIconData(0xe9f2);
  static const IconData icon_trending_down = const FeatherIconData(0xe9f3);
  static const IconData icon_trending_up = const FeatherIconData(0xe9f4);
  static const IconData icon_triangle = const FeatherIconData(0xe9f5);
  static const IconData icon_truck = const FeatherIconData(0xe9f6);
  static const IconData icon_tv = const FeatherIconData(0xe9f7);
  static const IconData icon_twitch = const FeatherIconData(0xe9f8);
  static const IconData icon_twitter = const FeatherIconData(0xe9f9);
  static const IconData icon_type = const FeatherIconData(0xe9fa);
  static const IconData icon_umbrella = const FeatherIconData(0xe9fb);
  static const IconData icon_underline = const FeatherIconData(0xe9fc);
  static const IconData icon_unlock = const FeatherIconData(0xe9fd);
  static const IconData icon_upload = const FeatherIconData(0xe9fe);
  static const IconData icon_upload_cloud = const FeatherIconData(0xe9ff);
  static const IconData icon_user = const FeatherIconData(0xea00);
  static const IconData icon_user_check = const FeatherIconData(0xea01);
  static const IconData icon_user_minus = const FeatherIconData(0xea02);
  static const IconData icon_user_plus = const FeatherIconData(0xea03);
  static const IconData icon_user_x = const FeatherIconData(0xea04);
  static const IconData icon_users = const FeatherIconData(0xea05);
  static const IconData icon_video = const FeatherIconData(0xea06);
  static const IconData icon_video_off = const FeatherIconData(0xea07);
  static const IconData icon_voicemail = const FeatherIconData(0xea08);
  static const IconData icon_volume = const FeatherIconData(0xea09);
  static const IconData icon_volume_1 = const FeatherIconData(0xea0a);
  static const IconData icon_volume_2 = const FeatherIconData(0xea0b);
  static const IconData icon_volume_x = const FeatherIconData(0xea0c);
  static const IconData icon_watch = const FeatherIconData(0xea0d);
  static const IconData icon_wifi = const FeatherIconData(0xea0e);
  static const IconData icon_wifi_off = const FeatherIconData(0xea0f);
  static const IconData icon_wind = const FeatherIconData(0xea10);
  static const IconData icon_x = const FeatherIconData(0xea11);
  static const IconData icon_x_circle = const FeatherIconData(0xea12);
  static const IconData icon_x_octagon = const FeatherIconData(0xea13);
  static const IconData icon_x_square = const FeatherIconData(0xea14);
  static const IconData icon_youtube = const FeatherIconData(0xea15);
  static const IconData icon_zap = const FeatherIconData(0xea16);
  static const IconData icon_zap_off = const FeatherIconData(0xea17);
  static const IconData icon_zoom_in = const FeatherIconData(0xea18);
  static const IconData icon_zoom_out = const FeatherIconData(0xea19);
}
